#!/bin/bash
export BOTTLE_PORT=8081
export BOTTLE_RELOADER=1
export BOTTLE_ROOT=${JUPYTERHUB_SERVICE_PREFIX}proxy/${BOTTLE_PORT}/
export BOTTLE_RUNTIME=aplikacija.py
export POSTGRES_PORT=443
python ${BOTTLE_RUNTIME} &
exec "$@"